# "window.opacity" = 1.0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#686868"
blue = "#5CCFE6"
cyan = "#95E6CB"
green = "#A6CC70"
magenta = "#FFEE99"
red = "#F27983"
white = "#FFFFFF"
yellow = "#FFCC66"

[colors.normal]
black = "#191E2A"
blue = "#73D0FF"
cyan = "#95E6CB"
green = "#BAE67E"
magenta = "#FFD580"
red = "#FF3333"
white = "#C7C7C7"
yellow = "#FFA759"

[colors.primary]
background = "#202734"
foreground = "#CBCCC6"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

# [schemes.argonaut.bright]
# black = "0x6D7070"
# blue = "0x1BA6FA"
# cyan = "0x73FBF1"
# green = "0xB8E466"
# magenta = "0xA578EA"
# red = "0xFF4352"
# white = "0xFEFEF8"
# yellow = "0xFFD750"
# 
# [schemes.argonaut.cursor]
# cursor = "0xFF261E"
# text = "0xFF261E"
# 
# [schemes.argonaut.normal]
# black = "0x0d0d0d"
# blue = "0x1BA6FA"
# cyan = "0x21DEEF"
# green = "0xA0E521"
# magenta = "0x8763B8"
# red = "0xFF301B"
# white = "0xEBEBEB"
# yellow = "0xFFC620"
# 
# [schemes.argonaut.primary]
# background = "0x292C3E"
# foreground = "0xEBEBEB"
# 
# [schemes.doom-one.bright]
# black = "#5b6268"
# blue = "#3071db"
# cyan = "#46d9ff"
# green = "#4db5bd"
# magenta = "#a9a1e1"
# red = "#da8548"
# white = "#dfdfdf"
# yellow = "#ecbe7b"
# 
# [schemes.doom-one.cursor]
# cursor = "#528bff"
# text = "CellBackground"
# 
# [schemes.doom-one.normal]
# black = "#1c1f24"
# blue = "#51afef"
# cyan = "#5699af"
# green = "#98be65"
# magenta = "#c678dd"
# red = "#ff6c6b"
# white = "#202328"
# yellow = "#da8548"
# 
# [schemes.doom-one.primary]
# background = "#282c34"
# foreground = "#bbc2cf"
# 
# [schemes.doom-one.selection]
# background = "#3e4451"
# text = "CellForeground"
# 
# [schemes.dracula.bright]
# black = "#4d4d4d"
# blue = "#caa9fa"
# cyan = "#9aedfe"
# green = "#5af78e"
# magenta = "#ff92d0"
# red = "#ff6e67"
# white = "#e6e6e6"
# yellow = "#f4f99d"
# 
# [schemes.dracula.cursor]
# cursor = "CellForeground"
# text = "CellBackground"
# 
# [schemes.dracula.dim]
# black = "#14151b"
# blue = "#4d5b86"
# cyan = "#59dffc"
# green = "#1ef956"
# magenta = "#ff46b0"
# red = "#ff2222"
# white = "#e6e6d1"
# yellow = "#ebf85b"
# 
# [schemes.dracula.line_indicator]
# background = "None"
# foreground = "None"
# 
# [schemes.dracula.normal]
# black = "#000000"
# blue = "#bd93f9"
# cyan = "#8be9fd"
# green = "#50fa7b"
# magenta = "#ff79c6"
# red = "#ff5555"
# white = "#bfbfbf"
# yellow = "#f1fa8c"
# 
# [schemes.dracula.primary]
# background = "#282a36"
# foreground = "#f8f8f2"
# 
# [schemes.dracula.search.bar]
# background = "#282a36"
# foreground = "#f8f8f2"
# 
# [schemes.dracula.search.focused_match]
# background = "#ffb86c"
# foreground = "#44475a"
# 
# [schemes.dracula.search.matches]
# background = "#50fa7b"
# foreground = "#44475a"
# 
# [schemes.dracula.selection]
# background = "#44475a"
# text = "CellForeground"
# 
# [schemes.dracula.vi_mode_cursor]
# cursor = "CellForeground"
# text = "CellBackground"
# 
# [schemes.remedy_dark.bright]
# black = "0x373b41"
# blue = "0x81a2be"
# cyan = "0x8abeb7"
# green = "0xb5bd68"
# magenta = "0xb294bb"
# red = "0xcc6666"
# white = "0xc5c8c6"
# yellow = "0xf0c674"
# 
# [schemes.remedy_dark.cursor]
# cursor = "0xf9e7c4"
# text = "0xf9e7c4"
# 
# [schemes.remedy_dark.normal]
# black = "0x282a2e"
# blue = "0x5f819d"
# cyan = "0x5e8d87"
# green = "0x8c9440"
# magenta = "0x85678f"
# orange = "0xcc6953"
# red = "0xa54242"
# white = "0x707880"
# yellow = "0xde935f"
# 
# [schemes.remedy_dark.primary]
# background = "0x2c2b2a"
# bright_background = "0x353433"
# bright_foreground = "0x1C1508"
# dim_background = "0x202322"
# dim_foreground = "0x685E4A"
# foreground = "0xf9e7c4"
# 
# [schemes.solarized-dark.bright]
# black = "#002b36"
# blue = "#839496"
# cyan = "#93a1a1"
# green = "#586e75"
# magenta = "#6c71c4"
# red = "#cb4b16"
# white = "#fdf6e3"
# yellow = "#657b83"
# 
# [schemes.solarized-dark.cursor]
# cursor = "#839496"
# text = "#002b36"
# 
# [schemes.solarized-dark.normal]
# black = "#073642"
# blue = "#268bd2"
# cyan = "#2aa198"
# green = "#859900"
# magenta = "#d33682"
# red = "#dc322f"
# white = "#eee8d5"
# yellow = "#b58900"
# 
# [schemes.solarized-dark.primary]
# background = "#002b36"
# foreground = "#839496"
# 
# [schemes.solarized-light.bright]
# black = "#002b36"
# blue = "#839496"
# cyan = "#93a1a1"
# green = "#586e75"
# magenta = "#6c71c4"
# red = "#cb4b16"
# white = "#fdf6e3"
# yellow = "#657b83"
# 
# [schemes.solarized-light.cursor]
# cursor = "#657b83"
# text = "#fdf6e3"
# 
# [schemes.solarized-light.normal]
# black = "#073642"
# blue = "#268bd2"
# cyan = "#2aa198"
# green = "#859900"
# magenta = "#d33682"
# red = "#dc322f"
# white = "#eee8d5"
# yellow = "#b58900"
# 
# [schemes.solarized-light.primary]
# background = "#fdf6e3"
# foreground = "#657b83"

[scrolling]
history = 5000

[window]
dynamic_padding = false
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
